#
b C:\dev\repositorios\progress\progress\database\
#
d "Schema Area":6,32;1 C:\dev\repositorios\progress\progress\database\
#
d "Employee":7,32;1 C:\dev\repositorios\progress\progress\database\ f 320
d "Employee":7,32;1 C:\dev\repositorios\progress\progress\database\
#
d "Inventory":8,32;1 C:\dev\repositorios\progress\progress\database\ f 640
d "Inventory":8,32;1 C:\dev\repositorios\progress\progress\database\
#
d "Cust_Data":9,32;1 C:\dev\repositorios\progress\progress\database\ f 320
d "Cust_Data":9,32;1 C:\dev\repositorios\progress\progress\database\
#
d "Cust_Index":10,32;1 C:\dev\repositorios\progress\progress\database\ f 320
d "Cust_Index":10,32;1 C:\dev\repositorios\progress\progress\database\
#
d "Order":11,32;1 C:\dev\repositorios\progress\progress\database\ f 1280
d "Order":11,32;1 C:\dev\repositorios\progress\progress\database\
#
d "Misc":12,32;1 C:\dev\repositorios\progress\progress\database\ f 320
d "Misc":12,32;1 C:\dev\repositorios\progress\progress\database\
